// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufdcxuhkvorygberosmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmZGN4dWhrdm9yeWdiZXJvc21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODY2NjUsImV4cCI6MjA2NDk2MjY2NX0.oboMdbmi9aWH5k0EWWzfrMFVunRszR7r7pqg3238toY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);